### ISSUE TITLE
setTimestring

### ISSUE THREAD

**Issue by aknik** [mazzoo/dcf77#1]
Debian 9 64bits
Compaq c700 laptop

usuario@debian:~/dcf77$ make
gcc -Wall dcf77.c -L/usr/X11R6/lib -lpthread -lXxf86vm -lXaw -lX11 -lSDL -o dcf77
/tmp/ccl509I0.o: En la función `setTimestring':
dcf77.c:(.text+0x302): referencia a `parity_min_hour' sin definir
dcf77.c:(.text+0x425): referencia a `parity_min_hour' sin definir
dcf77.c:(.text+0x7cd): referencia a `parity_day_thru_year' sin definir
collect2: error: ld returned 1 exit status
Makefile:4: fallo en las instrucciones para el objetivo 'dcf77'
make: *** [dcf77] Error 1

**Comment by mazzoo** [comment]
can you run
LANG=en make
so I can have more of a clue what happens on your machine...

**Comment by LangerJan** [comment]
This is what I fixed with my pull request
